catalog/urls.py
from django.conf.urls import include, url
from . import views


# Application URL Mapper
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^authors/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
]

# User Loaned Book URL Conf
urlpatterns += [
	url(r'^mybooks/$', views.LoanedBookUserListView.as_view(), name='borrowed-book'),
	url(r'^borrowed/$', views.AllBorrowedBookListView.as_view(), name='all-borrowed-book'),
]

# Renew Book URL Conf
urlpatterns += [
	url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book, name='renew-book'),
]

# Author Model URL Conf
urlpatterns += [
	url(r'^author/create/$', views.AuthorCreate.as_view(), name='author-create'),
	url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author-update'),
	url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author-delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView


# Admin Interface Mapper
urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Redirect to Catalog URL Mapper
urlpatterns += [
	url(r'^catalog/', include('catalog.urls')),
	url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Authentication URL
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]


# Use static to add url mapping to server static files for local development only
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import User
from datetime import date
from django.db import models
from django.urls import reverse 	# Used to generate URLS by reversing the URL patterns
import uuid


class Genre(models.Model):
	name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

	def __str__(self):
		return self.name


class Book(models.Model):
	title 		= models.CharField(max_length=200)
	author 		= models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
	summary 	= models.TextField(max_length=1000, help_text="Enter a brief description of the book")
	isbn 		= models.CharField('ISBN', max_length=13, help_text="13 Characters ISBN number")
	genre 		= models.ManyToManyField(Genre, help_text="Select a genre for this book")

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		return  ', '.join([genre.name for genre in self.genre.all()])
	
	display_genre.short_description = 'Genre'


class BookInstance(models.Model):
	id 			= models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book in Library")
	book 		= models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
	imprint 	= models.CharField(max_length=200)
	due_back 	= models.DateField(null=True, blank=True)
	borrower 	= models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On Loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book Availability')

	class Meta:
		ordering = ["due_back"]
		permissions = (("can_mark_returned", "Set book as returned"),)

	def __str__(self):
		return '{0} ({1})'.format(self.id, self.book.title)

	@property
	def is_overdue(self):
		if self.due_back and date.today() > self.due_back:
			return True
		return False


class Author(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)	
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True)

	def get_absolute_url(self):
		return reverse('author-detail', args=[str(self.id)])

	def __str__(self):
		return '{0}, {1}'.format(self.last_name, self.first_name)

catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from datetime import date, timedelta
from django import forms


class RenewBookForm(forms.Form):
	renewal_date = forms.DateField(help_text="Enter a date between today and 4 weeks (default 3).")

	def clean_renewal_date(self):
		data = self.cleaned_data['renewal_date']

		if data < date.today():
			raise ValidationError(_('Invalidate date - renewal in past'))

		if data > date.today() + timedelta(weeks=4):
			raise ValidationError(_('Invalidate date - renewal more than 4 weeks ahead'))
			
		return data

catalog/views.py
from datetime import date, timedelta
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book, BookInstance, Author, Genre 
from .forms import RenewBookForm


def index(request):
	num_books 		= Book.objects.all().count()
	num_instances 	= BookInstance.objects.all().count()

	num_instances_available 	= BookInstance.objects.filter(status__exact='a').count()
	num_authors 				= Author.objects.all().count()

	context = {
		'num_books': num_books,
		'num_instances': num_instances,
		'num_instances_available': num_instances_available,
		'num_authors': num_authors,
	}

	return render(request, 'index.html', context)



class BookListView(ListView):
	model = Book	
	template_name = 'book_list.html'
	paginate_by = 25


class BookDetailView(LoginRequiredMixin, DetailView):
	model = Book
	template_name = 'book_detail.html'


class AuthorListView(ListView):
	model = Author
	template_name = 'authors.html'
	paginate_by = 25


class AuthorDetailView(LoginRequiredMixin, DetailView):
	model = Author
	template_name = 'author_detail.html'


class LoanedBookUserListView(LoginRequiredMixin, ListView):
	model = BookInstance
	template_name = 'borrowed_book.html'
	paginate_by = 10

	def get_queryset(self):
		return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('-due_back')


class AllBorrowedBookListView(PermissionRequiredMixin, ListView):
	model = BookInstance
	template_name = 'all_borrowed_book.html'
	paginate_by = 25
	permission_required = 'catalog.can_mark_returned'



def renew_book(request, pk):
	book_instance = get_object_or_404(BookInstance, pk=pk)

	if request.method == 'POST':
		form = RenewBookForm(request.POST)

		if form.is_valid():
			book_instance.due_back = form.cleaned_data['renewal_date']
			book_instance.save()

			return HttpResponseRedirect(reverse('all-borrowed-book'))

	else:
		proposed_renewal_date = date.today() + timedelta(weeks=3)
		form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})		

	context = {
		'form': form,
		'book_instance': book_instance,
	}	

	return render(request, 'renew_book.html', context)



class AuthorCreate(PermissionRequiredMixin, CreateView):
	model = Author
	template_name = 'author_form.html'
	fields = '__all__'
	permission_required = 'catalog.can_mark_returned'
	

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
	model = Author
	template_name = 'author_form.html'
	fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
	permission_required = 'catalog.can_mark_returned'


class AuthorDelete(PermissionRequiredMixin, DeleteView):
	model = Author
	template_name = 'author_confirm_delete.html'
	success_url = reverse_lazy('authors')
	permission_required = 'catalog.can_mark_returned'

catalog/templates/all_borrowed_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>
      {% for bookinstance in bookinstance_list %}
      {% if bookinstance.status == 'o' %} 
      <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a> ({{ bookinstance.due_back }}) - 
        <a href="">{{ bookinstance.borrower }}</a> 

        {% if perms.catalog.can_mark_returned %} -
        <a href="{% url 'renew-book' bookinstance.pk %}">Renew</a>
        {% endif %}
      </li>
      {% endif %}
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/author_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/author_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Author: {{ author.last_name }}, {{ author.first_name }}</h1>

  <p>{{ author.date_of_birth}} - {% if author.date_of_death %} {{ author.date_of_death }} {% else %}</p> {% endif %}
  <ul style="list-style:  none;"><h3>Books</h3> 
    {% for author_book in author.book_set.all %}
      <h4><a href="{{ author_book.get_absolute_url }}"><strong>{{ author_book.title }}</strong></a></h4>
      <p>{{ author_book.summary }}</p><hr>
    {% endfor %}
  <ul>
  
{% endblock %}

catalog/templates/author_form.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/authors.html
{% extends 'base.html' %}
{% block content %}
<h1>Author List</h1>

{% if author_list %}
<ul>
{% for author in author_list %}
  <li>
    <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
    {% if perms.catalog.can_mark_returned %} -
    <a href="{% url 'author-update' author.pk %}">Edit</a> - 
    <a href="{% url 'author-delete' author.pk %}">Delete</a>
    {% endif %}
  </li> 
{% endfor %}
</ul>

{% else %}
<p>There are no authors available.</p>
{% endif %}
{% endblock content %}

catalog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All Books</a></li>
          <li><a href="{% url 'authors' %}">All Authors</a></li><hr>
      {% if user.is_authenticated %}
          <li><strong>User: {{ user.get_username }}</strong></li>
          <li><a href="{% url 'borrowed-book' %}">My Borrowed</a></li><br>
          <!-- Appending ?next=request.path: 'next' contains current URL page where user is located and 
          redirects the user back to the page where they clicked login/logout link -->
          <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li> 
          {% else %}
          <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
          {% endif %}
          {% if perms.catalog.can_mark_returned %}
          <hr><li>Staff</li>
          <li><a href="{% url 'all-borrowed-book' %}">All Borrowed</a></li>
          <li><a href="{% url 'author-create' %}">Add Author</a></li>
          {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
      {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
      {% endif %}
      {% endblock %}

      </div>
    </div>

  </div>
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</body>
</html>

catalog/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p> 
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Genre:</strong> 
  {% for genre in book.genre.all %} {{ genre }}
    {% if not forloop.last %}, {% endif %}
  {% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %} text-success {% elif copy.status == 'm' %} text-danger {% else %} text-warning {% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/book_list.html
{% extends 'base.html' %}
{% block content %}
<h1>Book List</h1>

{% if book_list %}
<ul>
{% for book in book_list %}
  <li>
    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
  </li>
{% endfor %}
</ul>

{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock content %}

catalog/templates/borrowed_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinstance in bookinstance_list %} 
      <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinstance.book.pk %}">{{bookinstance.book.title}}</a> ({{ bookinstance.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Library Home</h1>

<p>The library has the following record counts:</p>
<ul>
  <li><strong>Books: </strong>{{ num_books }}</li>
  <li><strong>Copies: </strong>{{ num_instances }}</li>
  <li><strong>Copies Available: </strong>{{ num_instances_available }}</li>
  <li><strong>Authors: </strong>{{ num_authors }}</li>
</ul>

{% endblock content %}

catalog/templates/renew_book.html
{% extends 'base.html' %}
{% block content %}

    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>
    
    <form action="" method="POST">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}